### PR TITLE
multi: remove repetitive the

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Comment by kcalvinalvin** [comment]
Could you change the commit message to:

`multi: remove repetitive the`

LGTM otherwise

**Review by halseth — APPROVED** [review]
LGTM

**Review by guggero — APPROVED** [review]

**Comment by kcalvinalvin** [comment]
Seems like that one test that occasionally fails is failing.

I can't run the CI again but you could trigger the CI by an empty

`git commit --amend` and change the commit hash.

**Comment by guggero** [comment]
Can confirm the CI failure was a flake.

**Pull request merged**
