### PR TITLE
txscript: Fix typo in README 📝

### PR DESCRIPTION
**Pull request by shphrd**
langauge ---> language

[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/613)

### CODE REVIEW

**Comment by davecgh** [comment]
Thanks!  OK.

**Comment by davecgh** [comment]
Actually I just saw the commit message doesn't match the PR title.  Would you amend the commit message to put the subsystem first and then for push to update this PR?

```bash
$ git commit --amend -m "txscript: Fix typo in README"
```

**Comment by shphrd** [comment]
Fixed. 😃

**Comment by davecgh** [comment]
Thanks.

**Pull request merged**
