### PR TITLE
Added testnet and simnet to rpcclient

### PR DESCRIPTION
**Pull request by kryptodirect**
You can declare the type of Netmode you want to use in config. Defaults to MainNet 

The options are:
-Mainnet
-Simnet
-Testnet

### CODE REVIEW

**Comment by Rjected** [comment]
How is this different from #1467?

**Comment by jakesyl** [comment]
@jcvernaleo (as per #1530)

- high priority
- feature

Contained in #1467 (which also fixes an issue around `type()`

**Comment by jcvernaleo** [comment]
@jakesyl @Rjected with #1467 in, can I close this one as obsolete?  Seems like it to me but want to confirm.

**Comment by jakesyl** [comment]
Id day so- this just looks like a more explicit implementation

**Pull request closed without merging**
