### PR TITLE
simplify s[:] to s where s is a slice

### PR DESCRIPTION
**Pull request by quasilyte**
Found using https://go-critic.github.io/overview#unslice-ref

### CODE REVIEW

**Comment by jakesyl** [comment]
@jcvernaleo (as per #1530)

- Low priority

Just a formatting fix

**Comment by jakesyl** [comment]
@jcvernaleo (as per #1530)

- Low priority

Just a formatting fix (but in the code, not in a comment so use more caution than #1398/#1475/#1507 when merging

**Comment by jakesyl** [comment]
@quasilyte if you do a force push, I'm good to approve and get this merged once tests are passing

**Comment by onyb** [comment]
Superseded by #1666.

**Pull request closed without merging**
