### PR TITLE
multi: Update with result of gofmt -s.

### PR DESCRIPTION
**Pull request by davecgh**
This pull request updates the code to make use of the most recent simplified output from gofmt.

[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/636)

### CODE REVIEW

**Comment by jrick** [comment]
README needs to be updated saying it required Go 1.5.

**Comment by davecgh** [comment]
These changes shouldn't require Go 1.5.  It passed Travis which still runs Go 1.4.2 as well.

**Comment by jrick** [comment]
I suppose, but only because there are no map key literals that were simplified.

https://golang.org/doc/go1.5#language

**Comment by davecgh** [comment]
Right, I recall seeing that addition to 1.5, but there were no cases of that here.

**Comment by jrick** [comment]
Since my only complaint was fixed separately on master: ok

**Comment by davecgh** [comment]
Even though this doesn't require it anyways, the README has been updated for Go 1.6 via #638.

**Pull request merged**
