### PR TITLE
rpcserver: Fix 9 typos in comments

### PR DESCRIPTION
**Pull request by tb00**
[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/634)

### CODE REVIEW

**Comment by jcvernaleo** [comment]
Nice catches.
OK

**Comment by davecgh** [comment]
Thanks for catching those and submitting a PR.

OK

**Comment by davecgh** [comment]
@tb00: By the way, if you're at all considering changing anything in the RPC server, I'd suggest taking a look at #491 as it has a ton of changes for the RPC server that will be deployed as soon as I finish the new indexing infrastructure and addridx/txidx which I'm currently working on in order to finish the major infrastructure changes for the new database.

**Comment by tb00** [comment]
@davecgh: Yes, thanks for the heads up. I have looked at #491 a couple of times the last few weeks. I will make sure not to duplicate efforts and will only send one or two trivial PRs that do not interfere with what you are working on.

**Pull request merged**
