### PR TITLE
Fix the signature bug. Change doubleGeneric and doubleZ1EqualsOne to …

### LINKED ISSUE #709: btcec: recovers certain signature without error
I am trying to use package btcec in go-ethereum for the sake of having a pure-go build.
During testing, I discovered that btcec.RecoverCompact accepts certain signatures which
are rejected by both libsecp256k1 and the ECDSA_SIG_recover_key_GFp function previously
used in bitcoind (before they switched to libsecp256k1).

The signature and message in question are:

``` text
msg = 00c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c
sig = 1c00b1693892219d736caba55bdb67216e485557ea6b6af75f37096c9aa6a5a75f00b940b1d03b21e36b0e47e79769f095fe2ab855bd91e3a38756b7d75a9c4549
```

See https://github.com/fjl/btcec-issue for code that reproduces the issue.
Output from `make test` in that repo (the signature above is sig 2):

``` text
== sig 1 libsecp256k1:
pubkey: 04E32DF42865E97135ACFB65F3BAE71BDC86F4D49150AD6A440B6F15878109880A0A2B2667F7E725CEEA70C673093BF67663E0312623C8E091B13CF2C0F11EF652
== sig 2 libsecp256k1:
recover failed
== sig 1 openssl:
pubkey: 04E32DF42865E97135ACFB65F3BAE71BDC86F4D49150AD6A440B6F15878109880A0A2B2667F7E725CEEA70C673093BF67663E0312623C8E091B13CF2C0F11EF652
== sig 2 openssl:
recover failed
== sig 1 btcec:
pubkey: 04E32DF42865E97135ACFB65F3BAE71BDC86F4D49150AD6A440B6F15878109880A0A2B2667F7E725CEEA70C673093BF67663E0312623C8E091B13CF2C0F11EF652
== sig 2 btcec:
pubkey: 04D808F6C95B99D15DC39CC452D5B1A37633455A3CC0B96B191AA1873A6174B00B4A58079675094B2459AA57E09505BF9A22DD6EB988FBB3A471B1F13D8D74CFF7
```

It might also be that I am using btcec.RecoverCompact incorrectly.

### PR DESCRIPTION
**Pull request by jimmysong**
…account for additional magnitudes.

Added a bunch of additional unit tests which I made while debugging.

This closes #709

### CODE REVIEW

**Comment by stevenroose** [comment]
I'd suggest moving the btcec_test package into btcec just like recently done with the wire package tests (#728) to avoid having to reveal the lambda and beta variables.

**Comment by dajohi** [comment]
@jimmysong Please rebase.

**Comment by jimmysong** [comment]
@dajohi This is now rebased.

**Comment by fjl** [comment]
Any news here?

**Comment by jimmysong** [comment]
@dajohi @davecgh Does this need rebasing again?

**Comment by davecgh** [comment]
As an update, I noticed that the specific changes made in this PR don't address the root issue even though it happens to resolve the specific case being testing.  The magnitudes in question are within range.  I've traced the real cause down to an issue in normalization.

As a result, I'm going to create a new PR that rewrites the normalization to both correct and optimize it.  I'll pare down the existing commit in this PR to only include the additional tests and NAF updates and include it in the other PR with your name on it to ensure you're given credit.

**Comment by davecgh** [comment]
Closing in favor of #960 which addresses the root cause.

**Pull request closed without merging**
