### PR TITLE
multi: catch up upstream btcd to roasbeef's fork

### PR DESCRIPTION
**Pull request by Roasbeef**
In this PR, we aim to catch up upstream btcd to my existing roasbeef fork. The fork has only been maintained due to legacy reasons: segwit wasn't yet merged in, and later on we start the work on BIP 157+158 (neutrino). The bulk of this PR is the legacy work that started on the BIP drafts (which later received numbers), the addition of the `estimatefee` command, upgrades to the `connmgr` to allow it to cancel pending connections not yet established, and various other bug fixes and tweaks we needed in order to get `lnd` working properly. 

Dependent on https://github.com/btcsuite/btcutil/pull/116.

### CODE REVIEW

**Comment by Roasbeef** [comment]
This won't build until the `btcsuite` PR is merged, and I update the glide files.

**Comment by stevenroose** [comment]
> This won't build until the btcsuite PR is merged, and I update the glide files. 

You mean btcutil there, right? So that should work now.

**Comment by Roasbeef** [comment]
Just pushed a new commit to address the new linter warnings.

**Comment by Roasbeef** [comment]
The build is now green 💚

**Comment by Roasbeef** [comment]
Have been running this on my nodes for the past few days, and haven't run into any major issues. Also FWIW, most of this code has already been merged into `dcrd`.

**Pull request merged**
