### PR TITLE
btcctl: Add getwalletinfo command

### PR DESCRIPTION
**Pull request by drazisil**
Adds wallet server command getwalletinfo

### CODE REVIEW

**Comment by davecgh** [comment]
Thanks for the PR.  Looks good.

OK

**Comment by dajohi** [comment]
OK..  but can you add the Result too?

See https://github.com/bitcoin/bitcoin/blob/master/src/wallet/rpcwallet.cpp#L2184-L2224

**Comment by dajohi** [comment]
but OK on this diff :)

**Comment by davecgh** [comment]
The result isn't needed for btcctl.  Once `btcwallet` implements the command, the result can be added then.

**Pull request merged**
