### PR TITLE
Formatting code with gofmt

### PR DESCRIPTION
**Pull request by huochexizhan**

### CODE REVIEW

**Comment by huochexizhan** [comment]
> lgtm
> 
> Should linting be added as part of the Github action checks?



> lgtm
> 
> Should linting be added as part of the Github action checks?

If the final conclusion needs to be added, I'm happy to submit a new PR to do it.

**Review by guggero — APPROVED** [review]
LGTM, thanks!

Would be nice to add linting/formatting to this project. The dockerized `tools` approach we use in `lnd` should be easy to port over: https://github.com/lightningnetwork/lnd/tree/master/tools

**Comment by huochexizhan** [comment]
> LGTM, thanks!
> 
> Would be nice to add linting/formatting to this project. The dockerized `tools` approach we use in `lnd` should be easy to port over: https://github.com/lightningnetwork/lnd/tree/master/tools

Thank you very much! I see you have approved it. Should I try to modify it on this PR or create a new one?

**Comment by guggero** [comment]
> Should I try to modify it on this PR or create a new one?

I think a new PR would be better, going to merge this one now.

**Comment by huochexizhan** [comment]
> > Should I try to modify it on this PR or create a new one?
> 
> I think a new PR would be better, going to merge this one now.

Thanks!

**Pull request merged**
