### PR TITLE
peer: Don't stall on pongs.

### PR DESCRIPTION
**Pull request by davecgh**
[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/534)

### CODE REVIEW

**Comment by jrick** [comment]
This makes a good case for reverting the always ping change that went in last week.  If we're on IBD and already have deadlines for getdata why do we need pings as well?  No point in sending them if we aren't going to bother checking for the pong.

**Comment by davecgh** [comment]
The main purpose of sending them is for updated ping statistics.

**Comment by jrick** [comment]
I'll throw in my ok on this one since the ping only exists to update stats.  The other deadlines should be sufficient to catch most stalls until multipeer is in.

**Comment by dajohi** [comment]
Seconded.

**Pull request merged**
