### PR TITLE
btcjson: Replace btcjson with version 2.

### PR DESCRIPTION
**Pull request by davecgh**
This commit removes the old and deprecated btcjsonv1 package, moves the new version 2 package into its place, and updates all imports accordingly.

**NOTE**

This pull request can't be merged until btcwallet and btcgui are updated to use version 2.  However, I wanted to have this pull request ready to go once those have been converted.

- [x] btcwallet
- [x] btcgui

### CODE REVIEW

**Comment by davecgh** [comment]
Rebased to latest master.

**Comment by davecgh** [comment]
Rebased to latest master and udpated for recent btcjson changes.

**Comment by davecgh** [comment]
This is now ready for merge after review.

**Comment by jrick** [comment]
ok

**Pull request merged**
