### PR TITLE
peer: Move AllowSelfConns into peer config

### PR DESCRIPTION
**Pull request by gtank**
Currently, the `NewOutboundPeer` [example](https://godoc.org/github.com/btcsuite/btcd/peer#example-package--NewOutboundPeer) in the docs can't actually work outside of the `peer_test` package. This change allows external users of the peer library to designate peer configs as explicitly for testing that will allow self-connections.

Closes https://github.com/btcsuite/btcd/issues/1464

### CODE REVIEW

**Comment by gtank** [comment]
Another approach to this would be to move `sentNonces` out of the global namespace. I'm not sure what approach the maintainers prefer, so I started with the one that seemed lowest impact.

**Comment by bjornoj** [comment]
Add a test?

**Comment by jakesyl** [comment]
@jcvernaleo (as per #1530)

- Low priority (doesn't affect node run as per #1464)
- Enhancement

**Comment by conradoplg** [comment]
Note that this was merged later in https://github.com/btcsuite/btcd/pull/1698 and this PR could be closed.

**Comment by jcvernaleo** [comment]
Thanks for point that out.  Closing this since the other PR covers it.

**Pull request closed without merging**
