### PR TITLE
mempool: Remove returned error from ProcessOrphans

### PR DESCRIPTION
**Pull request by dajohi**
ProcessTransaction could have accepted a new transaction into mempool
but could have returned a reject message if a no-longer-orphan
transaction failed to be accepted.  This would also skip any
additional no-longer-orphans, keeping them in the orphan pool.

Instead of returning an error incorrectly, log the error and skip
the no-longer-orphan transaction.  This allows the rest of the
no-longer-orphans to be processed as well.

[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/546)

### CODE REVIEW

**Comment by davecgh** [comment]
Commit message typos:

if an -> if a
would also skip the any -> would also skip any


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[mempool.go, line 1090 \[r1\]](https://reviewable.io:443/reviews/btcsuite/btcd/546#-K2nZHunhnLwh3ea9JC3)** ([raw file](https://github.com/btcsuite/btcd/blob/64efa3c30b518e4f08dcf16fc1eef5c3a7d36115/mempool.go#L1090)):</sup>
This defer is no longer needed since there is no longer a return.  No sense in having the extra overhead.

```Go
mp.Lock()
mp.processOrphans(hash)
mp.Unlock()
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/btcsuite/btcd/546)

**Comment by dajohi** [comment]
updated.

**Comment by davecgh** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/btcsuite/btcd/546)

**Comment by davecgh** [comment]
OK

**Comment by davecgh** [comment]
@jrick and I were talking about this and the TODO in the case where the length of missing parents is non-zero, it should be put back into the orphan pool and continue thereby skipping the relay.

**Comment by davecgh** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/btcsuite/btcd/546)

**Comment by davecgh** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/btcsuite/btcd/546)

**Comment by davecgh** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/btcsuite/btcd/546)

**Comment by jrick** [comment]
ok

**Comment by davecgh** [comment]
OK

**Pull request merged**
