### PR TITLE
Add 0.12.0 deps to deps.txt.

### PR DESCRIPTION
**Pull request by davecgh**
[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/554)

### CODE REVIEW

**Comment by jrick** [comment]
http://sprunge.us/AicQ 

Missing golangcrypto, snappy-go, and go-spew if you want to count that one too (although it isn't a btcsuite dep).

**Comment by davecgh** [comment]
Ah yes, we did vendor those.  Good catch.

**Comment by davecgh** [comment]
Updated to include `golangcrypto`and `snappy-go`.

**Comment by jrick** [comment]
ok

**Pull request merged**
