### PR TITLE
Blockverbose

### PR DESCRIPTION
**Pull request by zhiyuan2007**
fix bug #1230

getblock usage is:

getblock hash [0,1,2]

for  bitcoin-cli  and  btcctl

### CODE REVIEW

**Comment by reinerRubin** [comment]
@zhiyuan2007, bitcoin-core returns different tx types in the same tx field [1]. It can be "array of string" or "array of objects". Currently I am also trying to make a pr by adding extra structures to cover all verbosity outputs.

1 - http://chainquery.com/bitcoin-api/getblock

**Comment by reinerRubin** [comment]
@zhiyuan2007, I've made similar pr but now the client can call the bitcoin core and btcd-rpcserver.

**Comment by jakesyl** [comment]
@jcvernaleo (as per #1530)

- Low priority
- Enhancement
- Duplicate (of #1232), can probably close as that implementation has test cases attached

**Comment by jcvernaleo** [comment]
Closing this issue since there are other PRs that also cover it.  Sorry to have left PRs open long enough that we ended up with duplicates.  I hate wasting people's time like that.

**Pull request closed without merging**
