### PR TITLE
peer: Implement stall detection.

### LINKED ISSUE #486: BlockManager stops syncing during initial sync
I recently deployed btcd to a server with discoverability in order.

I noticed on getaddr.nodelist.io that the block height was no longer increasing (it was still catching up with the network), and this is what I found in the log:
https://gist.github.com/stevenroose/ce3003b8b61b86de5d11

Before that, it was processing blocks as normal, and suddenly it stops. After this excerpt are numerous lines of new connections and lost connections, mostly from `bitcoin-seeder` and `getaddr.bitnodes.io`.

### PR DESCRIPTION
**Pull request by davecgh**
**Requires #445**

*This is an alternative approach to #501 that is a more general solution and also fixes some concurrency-related issues with that PR as a side effect.*

This pull request implements stall detection logic at the peer level to detect and disconnect peers that are either not following the protocol in regards to expected response messages or have otherwise stalled.  This
is accomplished by setting deadlines for each message type which expects a response and periodically checking them while properly taking into account processing time.

There are an increasing number of nodes on the network which claim to be full nodes, but don't actually properly implement the entire p2p protocol even though they implement it enough to cause properly implemented nodes to make data requests to which they never respond.

Since btcd currently only syncs new blocks via single sync peer and, prior to this commit only had very basic stall detection, this could lead to a situation where the block download became stalled indefinitely due to one of these misbehaving peers.  This commit fixes that issue since the stalled peer will now be detected and disconnected which leads to a new sync peer being selected.

This logic will also fit nicely with the future multi-peer sync model which is on the roadmap and for which infrastructure work is underway.

Fixes #486 and #229 .

[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/518)

### CODE REVIEW

**Comment by davecgh** [comment]
Updated to improve log message on stalled peer and made it debug level.

**Comment by toddfries** [comment]
I used to have 'orphan block only' symptoms multiple times per day, but definately every 12-24hrs at the minimum... with this pull request, my btcd has not skipped a beat since.  Why is this not merged yet? ;-) ;-) ;-)

**Comment by dajohi** [comment]
No issues in hours with dozens of hosts.  OK

**Comment by jrick** [comment]
Reads like a hack but solves the immediate problem.  Although it's not a fool proof solution (deadlines can be overwritten for example) it will be updated when multipeer syncing is added.  ok

**Pull request merged**
