### PR TITLE
peer: Correct a few types in documentation.

### PR DESCRIPTION
**Pull request by davecgh**
[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/531)

### CODE REVIEW

**Comment by jcvernaleo** [comment]
This one looks good.  OK from me.

**Comment by jrick** [comment]
ok

**Comment by jrick** [comment]
although I do find the typo in the commit message to be a bit ironic

**Comment by davecgh** [comment]
Fixed the commit message typo too.

**Pull request merged**
