### PR TITLE
Bump Go versions

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
In my attempt to fix the formatting for 1.11, it broke for <1.11. So not sure how to fix this.

**Comment by zquestz** [comment]
@HaraldNordgren This should help you. I resolved this for bchd. https://github.com/gcash/bchd/pull/64

**Comment by HaraldNordgren** [comment]
@zquestz Thanks for the tip!

**Comment by HaraldNordgren** [comment]
@Roasbeef Ping

**Comment by Roasbeef** [comment]
Has been bumped in master already.

**Pull request closed without merging**
