### PR TITLE
Add VSize() for a transaction

### PR DESCRIPTION
**Pull request by FrozenPrincess**
See: https://bitcoincore.org/en/segwit_wallet_dev/#transaction-fee-estimation

### CODE REVIEW

**Comment by davecgh** [comment]
This is already available via the [mempool package as part of policy](http://godoc.org/github.com/btcsuite/btcd/mempool#GetTxVirtualSize).

**Comment by FrozenPrincess** [comment]
Ah, sorry. Didn't see it. Seems like a little bit of an awkward place to put it, but I'll close this as it already exists

**Comment by davecgh** [comment]
@Roasbeef can chime in as he put it there, but I think it makes sense because the virtual size is entirely a policy-related thing.  It's not something that is part of consensus nor required to serialize/deserialize at the protocol level.

**Comment by FrozenPrincess** [comment]
Yeah, fair enough. It's just that I had a `*MsgTx` and need to know it's vsize, it wasn't obvious that I'd need to convert to a `*Tx` and then use the mempool.  Now that I know about it however, it's not a big deal

**Comment by davecgh** [comment]
I would be in favor that function (and the one it calls in `blockchain`) over to accepting a `*wire.MsgTx` since there really isn't any reason for them to require a `*btcutil.Tx`.

**Pull request closed without merging**
