### PR TITLE
peer: use atomics instead of mutexes

### PR DESCRIPTION
**Pull request by dajohi**
This change is [Reviewable](https://reviewable.io/reviews/btcsuite/btcd/670)

### CODE REVIEW

**Comment by davecgh** [comment]
This is a reasonable change, however it will need to be tested on ARM and other 32-bit platforms since atomic relies on 64-bit alignment of the fields.  I believe the alignment is correct based on the field order, but given it will panic if not on 32-bit architectures, it's important to test it.

**Comment by dajohi** [comment]
I wonder if @T909 has the ability to test?

**Comment by davecgh** [comment]
For reference, I did test this on 32-bit Windows and it works without issue, so I'm pretty confident it will work properly on ARM as well.

**Comment by dajohi** [comment]
rebased

**Comment by davecgh** [comment]
OK

**Pull request merged**
