### PR TITLE
mempool: export checkStandardness func

### PR DESCRIPTION
**Pull request by ellemouton**
Export checkStandardness func so that it can be used elsewhere

### CODE REVIEW

**Review by Roasbeef — APPROVED** [review]
LGTM 🍁

It might also be useful to eventually export some more mempool components as well? So enough to be able to give it a mock UTXO set and apply the normal contextual validation. This might already be possible however. I think maybe we should defer merging this till the `lnd` PR using the new functionality gets further along so we can consider everything as a whole? No strong feelings in this direction fwiw.

**Comment by ellemouton** [comment]
>  I think maybe we should defer merging this till the lnd PR using the new functionality gets further along so we can consider everything as a whole?

yeah agreed. Just wanted to open this one up so long so that the go.mod in the LND pr is pointing to something visable

**Comment by Roasbeef** [comment]
We're seeing more instances of this in `lnd` when users end up creating mega transactions, so I think it's worth landing this, then circling back to see if we can add more contextual validation.

**Review by jcvernaleo — APPROVED** [review]
OK

**Pull request merged**
