### PR TITLE
btcec: set curve name in CurveParams

### LINKED ISSUE #1564: Set curve name for KoblitzCurve
All standard curves in Go standard package `crypto/elliptic` have its own name, e.g. `P-224`, `P-521`.
`KoblitzCurve` implementation should have its name, for example, `S-256` or `secp256k1` set.

### PR DESCRIPTION
**Pull request by hallazzang**
Set curve name(secp256k1) in KoblitzCurve.CurveParams

Fixes #1564

### CODE REVIEW

**Comment by hallazzang** [comment]
@onyb I chose the name `secp256k1` from that list. Is it worth adding comment like this?

```go
// Curve name taken from https://safecurves.cr.yp.to/.
secp256k1.Name = "secp256k1"
```

**Comment by onyb** [comment]
@hallazzang That seems fine to me. The idea for the comment was to justify why we use `secp256k1`, vs `S256`.

**Comment by Rjected** [comment]
Hi, do you mind rebasing this?

**Comment by hallazzang** [comment]
@Rjected updated.

**Review by jcvernaleo — APPROVED** [review]
OK

**Pull request merged**
