### PR TITLE
WIP: blockchain: implement new blockchain indexing infrastructure

### PR DESCRIPTION
**Pull request by Dirbaio**
**This PR requires #491**

As discussed with @davecgh over IRC, here's my proposed implementation for indexes on the new database.

Quick overview of the changes:

- Define a new interface, Index, with callbacks for connecting and disconnecting blocks.
- Add support in the blockchain package for enabling indexes when instancing a BlockChain.
- Make blockchain manage the lifecycle of index buckets, tracking of the index tips, catch up, call ConnectBlock/DisconnectBlock on the indexes. This avoids duplicating code per index type.
- Perform Block connection and index update atomically in the same database transaction.
- Add index registry, similar to the database2 driver registry, which enables registering indexes by name.
- Add new flags --index and --dropindex, for enabling and dropping indexes.
- Implement the old transaction-by-address as an index.

Indexes can be enabled and disabled at will. Dropping the index data is not necessary for disabling it, this allows a user to later re-enable an index without having to catch up from scratch again. Catch up works properly even if the index tip has been orphaned by a reorganize: catch up pops blocks from the index until the tip is back on the main chain, and then catches up to the main chain tip.

This introduces two new flags, --index and --dropindex. Both can be used multiple times to enable or drop several indexes, for example:
```
btcd --index=txbyaddr --index=txbyhash
```

For backwards compatibility, the --addrindex flag will be defined to be equivalent to --index=txbyaddr

The currently mandatory tx index will be rendered optional when @davecgh finishes work on the UTXO set: it can then be implemented as an optional index too. The flag --txindex could be added as an equivalent with --index=txbyhash for compatibility with Bitcoin Core.

TODO list:
- [ ] Make index catchup log progress like IBD and the old addrindex, and make it interruptible with ctrl+c.
- [x] Implement searchrawtransactions
- [x] Implement mempool addrindex
- [ ] Implement dropping indexes (--dropindex flag)
- [ ] Implement backwards-compatibility for -addrindex, same as --index=txbyaddr

[Review on Reviewable](https://reviewable.io/reviews/btcsuite/btcd/573)

### CODE REVIEW

**Comment by davecgh** [comment]
Thanks a lot for working on this.  I still have more to review, but I'll go ahead and publish the first round of comments.

---

Reviewed 36 of 42 files at r1, 7 of 7 files at r2, 34 of 34 files at r3, 9 of 15 files at r4.
Review status: 77 of 83 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[blockchain/chain.go, line 779 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4ZjGGulywKlyMzUECU:-K4ZjGGulywKlyMzUECV:874289221) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/blockchain/chain.go#L779)):*
This either needs to be done before the block insert above, or the code above needs to be changed to check the error.  Notice how it returns from the `if ! hasBlock` branch.

---

*[blockchain/chainio.go, line 445 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4fu9qxDZvHO6CTa2Fc:-K4fu9qykqUbw8L2bEQY:-1895471021) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/blockchain/chainio.go#L445)):*
Please add a TODO here so we don't forget to remove it once the txidx becomes optional.

---

*[blockchain/example_test.go, line 43 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4ZjnZNMzNXxLTepUaa:-K4ZjnZNMzNXxLTepUab:1809408452) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/blockchain/example_test.go#L43)):*
This comment should be updated with regards to the latest parameters.  I realize it wasn't done for the sigcache, but it should have been.

---

*[blockchain/index.go, line 126 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4ftrWVZNzOTZf7N4kA:-K4ftrWVZNzOTZf7N4kB:983131600) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/blockchain/index.go#L126)):*
This goes against [effective Go](https://golang.org/doc/effective_go.html#Getters) naming guidelines.    I'd suggest `IndexBucket` to be consistent with the naming guidelines.

---

*[config.go, line 128 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4Zk7GFckLCdwjigRkK:-K4Zk7GFckLCdwjigRkL:-1458006513) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/config.go#L128)):*
Manually listing the index names is bound to get out of date.  This should probably work something like the subsystems for the `DebugLevel` parameter.  See above for how it handles it.  For example something like "--index=show" would cause an early exist with a list of the available indexes.

---

*[index/log.go, line 1 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4fnaFHCIekYA43RypW:-K4fnaFIKsHc8rZW0eWa:1609329097) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/index/log.go#L1)):*
This is missing the license header.

```Go
// Copyright (c) 2015 The btcsuite developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.
```

---

*[index/registry.go, line 1 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4freI20beP_mHe_TSl:-K4freI20beP_mHe_TSm:1609329097) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/index/registry.go#L1)):*
This is missing the license header.

```Go
// Copyright (c) 2015 The btcsuite developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.
```

---

*[index/registry.go, line 9 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4fpf8YEy44ctp5VaR1:-K4fpf8Zd32gPsc69WGz:-1763902122) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/index/registry.go#L9)):*
Should be on the variable declaration itself instead of the entire variable block.

---

*[index/registry.go, line 25 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4fpv-hultcqGJ7D_rq:-K4fpv-iJldcRdcppOMM:127053172) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/index/registry.go#L25)):*
This goes against [effective Go](https://golang.org/doc/effective_go.html#Getters) naming guidelines.    I'd suggest `Indexes` to be consistent with the naming guidelines.

---

*[log.go, line 95 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4foDf5JD4sKuFfvYOk:-K4foDf6KcC3ijrve4pp:1868828173) ([raw file](https://github.com/btcsuite/btcd/blob/83bcfea271da8b0c890ede7ef374c5a74ec5aad7/log.go#L95)):*
The `AMGR`still exists and must not be removed.  It's the bitcoin peer (IP) address manager, not Bitcoin addresses.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/btcsuite/btcd/573#-:-K4Zl5O9x629lwVF9P8-:-1554769814)*

**Comment by Dirbaio** [comment]
Review status: 73 of 83 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[blockchain/chain.go, line 779 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4ZjGGulywKlyMzUECU:-K4tLrMO17VVc0QQ1VCv:-499146009) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/blockchain/chain.go#L779)):*
Done.

---

*[blockchain/chainio.go, line 445 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4fu9qxDZvHO6CTa2Fc:-K4tM2SSUwOmUocVwIfk:-499146009) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/blockchain/chainio.go#L445)):*
Done.

---

*[blockchain/example_test.go, line 43 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4ZjnZNMzNXxLTepUaa:-K4tMGAUb6tprqsjOw1I:-499146009) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/blockchain/example_test.go#L43)):*
Done.

---

*[blockchain/index.go, line 126 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4ftrWVZNzOTZf7N4kA:-K4tMarjY_GjSlzfzFXm:-499146009) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/blockchain/index.go#L126)):*
Done.

---

*[config.go, line 128 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4Zk7GFckLCdwjigRkK:-K4tMlZC0mTph6rm_3hm:1770382282) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/config.go#L128)):*
Good point, I'll implement this soon.

---

*[index/log.go, line 1 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4fnaFHCIekYA43RypW:-K4tGUfsHmNowRFRhI6b:-499146009) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/index/log.go#L1)):*
Done.

---

*[index/registry.go, line 1 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4freI20beP_mHe_TSl:-K4tLK382oKi6lXSAg_m:-499146009) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/index/registry.go#L1)):*
Done.

---

*[index/registry.go, line 9 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4fpf8YEy44ctp5VaR1:-K4tLUkNKRRZZohjfbn5:-499146009) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/index/registry.go#L9)):*
Done.

---

*[index/registry.go, line 25 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4fpv-hultcqGJ7D_rq:-K4tGssGpgNYzfbBX1Lg:-926777247) ([raw file](https://github.com/btcsuite/btcd/blob/6ea7dc8086157184b064dcb880cf817f8e016ad7/index/registry.go#L25)):*
Done. Renamed it to IndexesByName, it's more explicit in what it actually does

---

*[log.go, line 95 \[r4\]](https://reviewable.io:443/reviews/btcsuite/btcd/573#-K4foDf5JD4sKuFfvYOk:-K4tHGwpc9aQdPXK_uAG:775087548) ([raw file](https://github.com/btcsuite/btcd/blob/83bcfea271da8b0c890ede7ef374c5a74ec5aad7/log.go#L95)):*
Oops. 
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/btcsuite/btcd/573)*

**Comment by davecgh** [comment]
This needs a rebase over the latest blockchain_database2 branch which has now been updated to include the initial utxo set code.

**Comment by Dirbaio** [comment]
Rebased on latest #491.
Converted txindex to an index, it's optional now.
Removed the registry (It was useful for creating the indexes, but not for actually using them. The API'd be something like fetching them by name, casting them to the right struct, then calling methods on it.)

**Comment by davecgh** [comment]
Would you mind rebasing again over the latest and squashing the commits down.  I'm basically waiting on this now in order to get all of the chain work in, so if you're unable to work on it for a while, please let me know and I'll just finish up what you've done here.

**Comment by davecgh** [comment]
Discussed with the PR author some time ago and he did not have the cycles to complete it.  Closing in favor of #650 which has expanded upon, improved, and completed the work.

**Pull request closed without merging**
