### PR TITLE
Alphabetize --help output; add missing options to doc.go

### PR DESCRIPTION
**Pull request by murrayn**
Current --help output is a quite confusing. This change alphabetizes the output. Also update `doc.go`, alphabetizing and adding the following entries which are currently missing:

```
--addrindex
--blockmaxweight
--blockminweight
--dropaddrindex
--dropcfindex
--droptxindex
--rpcmaxconcurrentreqs
--trickleinterval
--txindex
```

### CODE REVIEW

**Comment by jakesyl** [comment]
@jcvernaleo (as per #1530)
- Low priority
- Outdated

**Comment by jakesyl** [comment]
@murrayn can we update this to get this merged?

**Comment by jakesyl** [comment]
Thanks!

**Comment by jcvernaleo** [comment]
Not sure why travis hasn't run for this yet.  Perhaps @Roasbeef or someone else has travis permissions that they can either look into it or give it a kick to make it go.

**Comment by jakesyl** [comment]
@jcvernaleo I've gone ahead and sent travis ci an email - my guess is it's a bug because of the force push that closed the PR (see the IRC for more details)

**Comment by jakesyl** [comment]
image


"Abuse detected"

**Comment by jcvernaleo** [comment]
So using travis counts as abuse now?  Awesome.

**Comment by jakesyl** [comment]
Alright, so apparently I've already solved this:

image

[see here](https://travis-ci.community/t/abuse-detected-for-my-prs-and-some-commits/6124/13)

guess we'll wait for a few days

**Comment by jakesyl** [comment]
image

**Comment by jakesyl** [comment]
@davecgh you think you can add one of us to the org? Sorry to bother you with this but I don't even think that github workflows will solve this since we can't back propagate it to old PRs

**Comment by davecgh** [comment]
Looks like pull request builds were turned off on Travis.  A force push should get it to build.

**Comment by jakesyl** [comment]
@murrayn sorry about this but would you mind just doing a quick force push?

@davecgh - so from what I've gotten from travis (see [here](https://github.com/btcsuite/btcd/pull/1329#issuecomment-606222044)), the `abuse detected` happens when users that are unknown submit prs and we need to request a rerun. This seems to happen randomly, and I'm currently working on a PR to move to github workflows, but all the older PRs are going to require a bunch of wrangling with the users to get these in.

Again - appreciate you taking the time to reply, I know you're super busy!

**Comment by murrayn** [comment]
@jakesyl I tried doing a 'git push -f' last week, but it didn't seem to have any effect. Any advice?

**Comment by davecgh** [comment]
It had no effect because the commit didn't change, so git doesn't have anything to do.  You can force it to change by using `git commit --amend --reset-author` which will update the timestamp and hence the commit will get a new hash and the force push will then update it and trigger a build.

**Comment by murrayn** [comment]
@davecgh thanks!

**Comment by githorray** [comment]
Unable to build on Windows after this merge.

$ go version
go version go1.14.2 windows/amd64

$ go install -v . ./cmd/...
github.com/btcsuite/btcd
# github.com/btcsuite/btcd
.\config.go:100: newline in string
, expecting semicolon or newline or }cted literal "`
.\config.go:110:24: syntax error: unexpected ] after top level declaration
.\config.go:169:36: syntax error: unexpected (, expecting name or (
.\config.go:170:2: syntax error: non-declaration statement outside function body

.\config.go:170:59: method has multiple receivers
.\config.go:171:2: syntax error: non-declaration statement outside function body

.\config.go:171:59: method has multiple receivers
.\config.go:172:2: syntax error: non-declaration statement outside function body

**Comment by davecgh** [comment]
Mentioned in the IRC channel along with the fix.  I believe rjected will be opening a PR to resolve it shortly.

**Pull request merged**
