### PR TITLE
rpctest: make sure to `WaitForShutdown`

### PR DESCRIPTION
**Pull request by yyforyongyu**
Make sure to call `WaitForShutdown` in the itest.

### CODE REVIEW

**Review by guggero — APPROVED** [review]

**Review by ellemouton — APPROVED** [review]

**Comment by yyforyongyu** [comment]
hold on i think it's breaking all test cases in `lnd`...

**Comment by yyforyongyu** [comment]
ok it's broken since this #2272

**Comment by yyforyongyu** [comment]
Now that the above issue is fixed think this can be merged.

**Comment by guggero** [comment]
Need another green review checkmark, don't have the perms to override merge otherwise... cc @Roasbeef

**Review by Roasbeef — APPROVED** [review]
LGTM 🍺

**Pull request merged**
